version: 1.0.0

# GO SDK使用的客户端部分。
client:
  # 客户端所属的组织，必须是organizations定义的组织
  organization: WW
  # 日志级别
  logging:
    level: info
  # MSP证书的根路径
  cryptoconfig:
    path: /network/crypto-config

# 通道定义
channels:
  appchannel:
    orderers:
      - orderer.swz.com
    peers:
      peer0.ww.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer1.ww.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

# 组织配置
organizations:
  JD:
    mspid: 'WWMSP'
    cryptoPath: peerOrganizations/ww.com/users/{username}@ww.com/msp
    peers:
      - peer0.ww.com
      - peer1.ww.com

# orderer节点列表
orderers:
  orderer.swz.com:
    url: orderer.swz.com:7050
    # 传递给gRPC客户端构造函数
    grpcOptions:
      ssl-target-name-override: orderer.swz.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: true

# peers节点列表
peers:
  # peer节点定义，可以定义多个
  peer0.ww.com:
    # URL用于发送背书和查询请求
    url: peer0.ww.com:7051
    # 传递给gRPC客户端构造函数
    grpcOptions:
      ssl-target-name-override: peer0.ww.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: true
  peer1.ww.com:
    url: peer1.ww.com:7051
    grpcOptions:
      ssl-target-name-override: peer1.ww.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: true
  peer0.zz.com:
    url: peer0.zz.com:7051
    grpcOptions:
      ssl-target-name-override: peer0.zz.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: true
  peer1.zz.com:
    url: peer1.zz.com:7051
    grpcOptions:
      ssl-target-name-override: peer1.zz.com
      keep-alive-time: 0s
      keep-alive-timeout: 20s
      keep-alive-permit: false
      fail-fast: false
      allow-insecure: true
